Path aliases for Libs folder
waghD/pr_service_engineering pull request #130
Opened 2022-02-03 13:56 UTC by waghD

closes #93

2022-02-03 14:24 UTC, vambi approved these changes

2022-02-08 05:45 UTC, rrancerr requested changes
![image](https://user-images.githubusercontent.com/51763897/152925602-01041684-1bf7-421b-8b01-a810639ac385.png)

Ich würde zumindest noch einen alias für den authstateservice machen.

Beim scss weiß ich ned in wie weit man da aliases anlegen kann bzw. der die auflösen kann - da sind halt auch noch 4 mal welche drin. Ich hab aber auch gesehen, dass wir das colors.scss unterschiedlich importieren, nicht als relativer pfad. Das wäre auch eine option

2022-02-08 18:22 UTC, waghD commented
Tjo der Code-Quality test war ned erfreut über den alias fürn AuthService 😬

Scheinbar will des keine Pfad aliase innerhalb vom projekt

Hab den commit nomal reverted

2022-02-08 18:23 UTC, vambi approved these changes

2022-02-08 18:23 UTC, rrancerr approved these changes

2022-02-08 18:23 UTC, merged