Classic game finalization
waghD/pr_service_engineering pull request #48
Opened 2021-12-03 13:36 UTC by rrancerr

Implements #32

2021-12-05 13:06 UTC, vambi approved these changes

2021-12-06 09:39 UTC, waghD requested changes

2021-12-06 09:39 UTC, waghD commented on apps/sudoku-frontend/src/app/pages/classic-game/classic-game.service.ts
> +      .put<any>(this.baseApiURL + '/sudokus/' + sudokuId, secondsOfTimer);
Kein Any. Bitte das richtige .dto interface als generic einfügen

2021-12-06 10:43 UTC, rrancerr commented on apps/sudoku-frontend/src/app/pages/classic-game/classic-game.service.ts
> +      .put<any>(this.baseApiURL + '/sudokus/' + sudokuId, secondsOfTimer);
hab jetzt die sudoku entity reingegeben, aber das ist auch nicht ganz korrekt, weil dieser API Endpunkt mit den meisten der properties nichts anfangen kann,

2021-12-08 13:09 UTC, vambi approved these changes

2021-12-09 12:30 UTC, waghD approved these changes

2021-12-09 12:31 UTC, waghD commented on apps/sudoku-frontend/src/app/pages/classic-game/classic-game.service.ts
> +      .put<any>(this.baseApiURL + '/sudokus/' + sudokuId, secondsOfTimer);
dann habn ma aber an scheiß beinand. Weil de .dta interfaces san jo dafür da um die http bodies für die rest api zu definieren

2021-12-09 12:32 UTC, merged