added diagonal sudoku
waghD/pr_service_engineering pull request #49
Opened 2021-12-08 15:20 UTC by vambi

2021-12-08 15:21 UTC, vambi commented
closes #38

2021-12-08 16:21 UTC, vambi commented
closes #42

2021-12-09 12:45 UTC, waghD requested changes

2021-12-09 12:45 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/controller/sudoku.controller.ts
> +   async generateSudoku(@Query('diagonal',new DefaultValuePipe(false),ParseBoolPipe) diagonal: boolean,){
Wir müssen noch mehrere sudoku varianten machen. Bitte etwas genereller halten.
type="diagonal" statt diagonal=true

2021-12-09 12:45 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/helpers/sudoku-solver.ts
> +function isPossibleNumber(cell: number, number: number, sudoku: number[], diagonal:boolean) {
Wieder, es gibt noch mehr varianten. Bitte generell halten.

2021-12-09 12:45 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/helpers/sudoku-solver.ts
> +  if(diagonal) return isPossibleRow(number,row,sudoku) && isPossibleCol(number,col,sudoku)
Same. Varianten generell halten

2021-12-09 12:45 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/helpers/sudoku-solver.ts
> +function determinePossibleValues(cell: number, sudoku: number[], diagonal:boolean) {
Same

2021-12-09 12:45 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/helpers/sudoku-solver.ts
> +function scanSudokuForUnique(sudoku: number[], diagonal:boolean): number[][] {
same

2021-12-09 12:45 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/models/sudoku.dto.ts
> +   diagonal:boolean;
same

2021-12-09 12:45 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/models/sudoku.entity.ts
> +  diagonal:boolean;
same

2021-12-09 12:45 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/service/sudoku-field.service.ts
> +  async generateSudokuFields(sudokuID:number, diagonal:boolean){
same

2021-12-09 12:45 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/service/sudoku.service.ts
> +  getSudokus(page = 1, take = 25, type:string): Promise<SudokuEntity[]> {
so is recht.

Aber was isn bei dir für a formattierung eingstellt? schaut jo schlimm aus

2021-12-09 17:19 UTC, waghD approved these changes

2021-12-09 17:19 UTC, rrancerr approved these changes

2021-12-09 17:20 UTC, merged