Add farbsudoku and farb diagonal sudoku
waghD/pr_service_engineering pull request #89
Opened 2022-01-04 11:16 UTC by vambi

Closes #61 #65

2022-01-09 16:16 UTC, rrancerr requested changes
bitte nicht wieder die package-lock.json committen, die 24.000 Zeilen code braucht glaub ich keiner

2022-01-10 09:44 UTC, waghD approved these changes

2022-01-10 09:51 UTC, waghD requested changes
color / colour

2022-01-10 09:51 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/service/sudoku-field.service.ts
> +         colors = coloursudoku.colors;
colors / colours

2022-01-10 09:51 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/service/sudoku-field.service.ts
> +      let colors;
colors / colours

2022-01-10 09:51 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/service/sudoku-field.service.ts
> +        colors2d = sudokuArrayTo2DArray(colors);
colors2d / colours2d

2022-01-10 09:51 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/helpers/sudoku-solver.ts
> +  colors: number[]
colors / colours

2022-01-10 09:51 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/helpers/sudoku-solver.ts
> +export function solveColourSudoku(sudoku: number[], colors:number[] ,type:string) {
colors / colours

2022-01-10 09:51 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/helpers/sudoku-solver.ts
> +      const colors = new Array<number>();
colors / colours

2022-01-10 09:51 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/helpers/sudoku-solver.ts
> +function returnColour(cell:number,number:number,colours:number [] ,possibleColors: number[] []){
possibleColors / possibleColours

2022-01-10 10:10 UTC, waghD requested changes
Ein colors hast no vergessen

2022-01-10 10:10 UTC, waghD commented on apps/sudoku-backend/src/app/sudoku/helpers/sudoku-solver.ts
> +      const colors = new Array<number>();
Des is immernu colors

2022-01-10 10:11 UTC, rrancerr approved these changes

2022-01-10 10:20 UTC, rrancerr approved these changes

2022-01-10 10:25 UTC, waghD approved these changes

2022-01-10 10:25 UTC, merged